kbaseurl = "http://localhost:1313/"
title = "Vicente Guerrero"

theme = "hugo-coder"

publishDir = "docs"

languagecode = "en"
defaultcontentlanguage = "en"
[markup.goldmark.renderer]
    unsafe = true # Allows you to write raw html in your md files


paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "yourdiscussshortname"

[params]
    author = "Vicente Guerrero"
    description = "Vicente Guerrero's personal website"
    keywords = "blog,developer,personal,software"
    info = "Freelace Software Developer"
    avatarurl = "images/about/vicente_2019-01-20_small.jpg"
    footercontent = "Let's do stuff together."

    dateformat = "January 2, 2020"

    hideCredits = false
    hideCopyright = false
    since = 2019

    # Git Commit in Footer, uncomment the line below to enable it.
    # commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorscheme = "light"

    # Series see also post count
    maxSeeAlsoItems = 5

    # Custom CSS
    custom_css = []
    
    # Custom JS
    custom_js = []

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[[params.social]]
    name = "Github"
    icon = "fab fa-github"
    weight = 1
    url = "https://github.com/viclule/"
[[params.social]]
    name = "Twitter"
    icon = "fab fa-twitter"
    weight = 3
    url = "https://twitter.com/chente_chente1/"
[[params.social]]
    name = "LinkedIn"
    icon = "fab fa-linkedin"
    weight = 4
    url = "https://www.linkedin.com/in/vicente-guerrero/"


[languages]
    [languages.en]
        languagename = "English"

        [languages.en.menu]

            [[languages.en.menu.main]]
            name = "About"
            weight = 1
            url = "about/"

            [[languages.en.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.en.menu.main]]
            name = "Services"
            weight = 3
            url = "services/"

            [[languages.en.menu.main]]
            name = "Contact me"
            weight = 5
            url = "contact/"


    [languages.de-DE]
        languagename = "Deutsch"
        title = "Vicente Guerrero"

        [languages.de-DE.params]
            author = "Vicente Guerrero"
            info = "Software Entwickler"
            description = "Personal Website von Vicente Guerrero"
            keywords = "blog,entwickler,software"
            footercontent = "Lass uns zusammen arbeiten."

        [languages.de-DE.menu]

            [[languages.de-DE.menu.main]]
            name = "Über"
            weight = 1
            url = "about/"

            [[languages.de-DE.menu.main]]
            name = "Blog"
            weight = 2
            url = "posts/"

            [[languages.de-DE.menu.main]]
            name = "Dienste"
            weight = 3
            url = "services/"

            [[languages.de-DE.menu.main]]
            name = "Kontakt"
            weight = 5
            url = "contact/"
